name-template: 'release-v$NEXT_PATCH_VERSION'
tag-template: 'release-v$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'docs: algorithm'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bug'
  - title: 'ğŸ§° Maintenance'
    labels:
      - 'dev experience'
      - 'enhancement'
      - 'dependencies'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # What's Changed

  $CHANGES
